DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS medical_data CASCADE;
DROP TABLE IF EXISTS person_locations CASCADE;
DROP TABLE IF EXISTS session_in_vacuum CASCADE;
DROP TABLE IF EXISTS outcome CASCADE;
DROP TYPE IF EXISTS gender;
DROP TYPE IF EXISTS health_status;
DROP TYPE IF EXISTS locations;
DROP FUNCTION IF EXISTS validate_pressure;
